### ISSUE TITLE
Setup a hotkey to switch between VDs in circular manner?

### ISSUE THREAD

**Issue by a-chakrawarti** [snaphat/virtual_desktop_enhancer#2]
Hi,

Let me start by saying this looks really cool, I am yet to try it out though. I was wondering if there is anyway to setup a hotkey to switch between VDs in a circular manner. I hope you got the gist of what I am trying to say but still let me elaborate.

- On pressing the hotkey, VD should move from Left to Right and when it encounters the rightmost VD, on pressing it again, it switches to the leftmost VD and same goes for the another hotkey which switches from Right to Left. Yea, like a carousel :D 
 
I goggled quite a lot to find something similar but no success. I gave reddit a shot and came across your post in r/Windows10. 

I don't have any idea on how to get started with ahk script, but over the weekend I might check it out.

Is this something possible using ahk script?

**Comment by snaphat** [comment]
It's possible, but not animatable in the way you'd expect. Basically you know how if you press ctrl-win-right, it animates moving the desktop to the right one and vice versa with the ctrl-win-left key? Well, you can't animate it along the edges since that's internally done by some windows APIs or something. But, a non-animated version could be done or even animated but the wrong direction....

For example, if you were on desktop 1, had 4 virtual desktops, and pressed ctrl-win-left you could have it animate moving in the opposite direction between 1..2..3...4, all the way to 5. Or you could just have it "appear" on 5 without any animation. Are either of those something you'd like?

**Comment by a-chakrawarti** [comment]
I think without the animation it would look nice. The thing is, I have a mouse with multiple buttons and are remappable. Currently, I have 2 dedicated switches assigned to <kbd>Win + Ctrl + -></kbd> and <kbd>Win + Ctrl + <-</kbd> to switch between the VDs. I want to cycle through the VDs just using a single dedicated button, either from L -> R or R -> L.

- Similar needs: https://superuser.com/questions/1176484/windows-virtual-desktops-cycle-back-to-first-desktop-at-end
- DesktopWrapping: https://github.com/sdias/win-10-virtual-desktop-enhancer/blob/master/docs/settings.md#main-settings

These are some that I found explains the feature better :D 

P.S. : I installed the script and its working beautifully.

**Comment by snaphat** [comment]
I'll attempt to add this today along with the fix for https://github.com/snaphat/virtual_desktop_enhancer/issues/3

**Comment by snaphat** [comment]
Please try https://github.com/snaphat/virtual_desktop_enhancer/releases/tag/v0.0.9. Note the configuration options that have been added (and documented on the main page). Both an "animated backwards" and non-animated version of looping have been implemented.

**Comment by snaphat** [comment]
I will note that the "animated" version seems better to me. The non-animated version seems a little slow because a 50ms delay is required so that spurious wakeups don't happen. The animated version has the same delay, but the animations kind of makes it less obvious.

Not sure if you tried, but if you tested the first ahk script you linked it loops/cycles faster, but causes spurious wakeups (blinking icons) because it doesn't have a built in delay. It's unfortunate but the windows APIs for virtual desktops are kind of terrible.

**Comment by a-chakrawarti** [comment]
I am loving this new feature! I still like the non-animated one, don't know why :D

- RAM usage is under 2MB and CPU is well within 1.5%.

Everything is working smoothly.

Thank you for the quick response. 👍

**Comment by a-chakrawarti** [comment]
I am closing this issue, nice work and again, thanks :D
